### ISSUE TITLE
Potential problem with using only one public key

### ISSUE THREAD

**Issue by Yuyz0112** [MartijnHols/WoWAnalyzer#117]
It seems we are using only one public key in production:
https://github.com/MartijnHols/WoWAnalyzer/blob/master/server/api.js#L38

In my experience of using WCL's api, it may face an error of 'Too many requests' with error code 429 when the number of concurrent request over the api limit.

Is this a potential problem which will broke WoW Analyzer when more players use this tool?

**Comment by MartijnHols** [comment]
Yes, it's a restriction by WCL. Nothing that can be done about it.

**Comment by Yuyz0112** [comment]
In my personal project I implemented a public keys load balancer.

I registered several WCL accounts and get multi public keys. Then I counted how much requests were sent by a key, so I can choose the lowest balance key and use it to send the next request.

**Comment by MartijnHols** [comment]
I don't think this would be a decent thing to do; if WCL wanted to allow more API requests by a single app, they'd increase the limit.

**Comment by Yuyz0112** [comment]
Sure, just a solution when there have no alternative way.
Contact the maintainer of WCL and apply for increasing the API limit is a better approach.

**Comment by MartijnHols** [comment]
Once we start running into this problem I'll talk to Kihra about it.
