### ISSUE TITLE
Items: Grawed Thumb Ring report

### ISSUE THREAD

**Issue by alivedise** [MartijnHols/WoWAnalyzer#123]
**What browser are you using?**
Chrome 59

**Link to an example report with the issue**
https://www.warcraftlogs.com/reports/BKJWR4FpgDx3Lvw8#fight=27&view=analytical&type=auras&source=3&ability=228461

https://wowanalyzer.com/report/BKJWR4FpgDx3Lvw8/27/%E5%BD%A4%E8%97%9C/cooldowns

**Expected behavior**
It shows "0.00 % / 0 HPS" in this ele shm's report. Not sure what you want to tell us? She did use the ring.

**Comment by MartijnHols** [comment]
Thanks for the report! That should of course show the damage contribution for DPS specs, totally forget about that when I made several items shared among all specs.

**Comment by Gurupitka** [comment]
Due to the nature of the ring should the page display both healing and damage increase amounts? I'm only thinking really of disc priests specifically where they would be getting both I imagine.

**Comment by alivedise** [comment]
Even so, it should not show healing done for ele spec shm.

**Comment by MartijnHols** [comment]
This was fixed with #132, closing issue.
