### ISSUE TITLE
[Suggestion] UX changes to fight selection

### ISSUE THREAD

**Issue by Nighteyez07** [MartijnHols/WoWAnalyzer#127]
Add the ability to select a UI item (like a pull down) for character and encounter to change to without having to load previous pages

**Current Behavior**
When examining a specific WCL record you must either use the back button or menu item that takes you back a screen to select a different character to analyze against. Then if you would like to change the encounter you have to go back yet again, select the different encounter, then select the character again.

**Suggested Behavior**
Using ToS as an example I recommend a UX change to the following. 

- Clicking the character name on the top breadcrumb displays all characters on the log whose specialization can be analyzed. Selecting character opens the analysis page

- Clicking the encounter name when on a current analysis page allows you to select a different encounter for the same character. So if Asmongold is currently looking at his character for the Goroth encounter he can click the UI element and be presented with a list of encounters that he can select. Upon selection it will then load that encounter for his same character.

**Comment by MartijnHols** [comment]
👍
I've been surprised nobody requested this earlier :') I've wanted to do since moving the fight selection before player selection, just never got around to it.

**Comment by MartijnHols** [comment]
This was fixed with #200, closing issue.
