### ISSUE TITLE
Setup a MariaDB container for the backend

### ISSUE THREAD

**Issue by MartijnHols** [MartijnHols/WoWAnalyzer#133]
I want a MariaDB database in the backend to take over caching and be able to build new features such as a queue system (best to build this before it's too late). My plans are to use a Docker container for this, but since I'm super new to Docker this makes it a lot harder for me.

- [x] Install Docker on my Windows pc
- [x] Figure out a MariaDB container on my Windows pc
- [ ] Figure out how to do migrations on the database
- [ ] Figure out how to do automated database backups
- [ ] Figure out how to do a MariaDB container on the server that's clean and obvious (e.g. make a dockerfile in the repo?)
- [ ] Write documentation how to set this up locally
- [ ] Figure out how to setup this container to only be exposed to the backend
- [ ] Figure out backups for the database
- [ ] Hide database connection info from code... or this might not be necessary as the DB could only be accessible from the container it gets exposed to, but this would still be best practice.

**Comment by Yuyz0112** [comment]
Good news.
But is docker going to be an develop dependency for developers? I think it increase the cost of starting contribute to this project.
So maybe we still need a fallback to let it work without dockerized MariaDB in develop env?

**Comment by MartijnHols** [comment]
It won't be a dev dependency just like the server isn't.

**Comment by Yuyz0112** [comment]
understood

**Comment by MartijnHols** [comment]
Desired situation:

Prod server has 2 containers running:
1. webserver
2. database server

When app gets updated only webserver gets restarted.
After restarting webserver the app runs database migrations (if available).
Database gets backupped automatically.
Database is only available internally to the webserver, not to the web. (this might change as I might want to be able to see the database content with HeidiSQL to spot issues)
Connection data is not revealed in the code but specified as secret in the Travis config.
Running the entire environment locally should be a breeze. 

I'd like to have the database server running during Travis builds so that it can be included in tests when desirable but I don't see either happening any time soon so I'll leave this for another time to reduce the scope of the current project.
