### ISSUE TITLE
Class/Spec not matching class color

### ISSUE THREAD

**Issue by Nighteyez07** [MartijnHols/WoWAnalyzer#163]
Making this official. Demon Hunter class color on front page is an affront to humanity...wowmanity? The peaceful serenity that is class harmony is off balance due to DH not utilizing the purple text color it should love and adore. This is a must fix for @Mamtooth.
![dh wowanalyzer](https://user-images.githubusercontent.com/20079828/29436754-00307b9e-8362-11e7-8852-636f5af662a2.PNG)

An honorary mention also goes to the fact that the specs are not listed in class ASC, spec ASC order.

**Comment by MartijnHols** [comment]
Thanks for the report; should be fixed in https://github.com/MartijnHols/WoWAnalyzer/commit/5c5b050653a10584b8977cb18fa1ef3f14c66aa9
