### ISSUE TITLE
Basic version for Mistweaver

### ISSUE THREAD

**Issue by MartijnHols** [MartijnHols/WoWAnalyzer#23]
Discord @Garg DMed me letting me know he would like to help making this in any way he can.

Need the following information:
 * List of all talents (see `common/SPELLS_TALENTS`
 * List of all abilities for CPM_ABILITIES
 * List of all abilities on the GCD for dead GCD time
 * List of all cooldowns (healing buffs like Innervate, Wings)

**Comment by garg** [comment]
Hi, I think you have the wrong person? I didn't DM you.

**Comment by MartijnHols** [comment]
Sorry this was Discord \@Garg.

**Comment by MartijnHols** [comment]
Related: #33
