### ISSUE TITLE
"Show less" for Cooldown tabs

### ISSUE THREAD

**Issue by buimichael** [MartijnHols/WoWAnalyzer#35]
Add a button to "Show less" when expanding "Show more" and "Even more".

**Comment by fasib** [comment]
b6861c4
A toggle Version with 
- `More` 
- `Even more` and `Show less`
- `Show less` and `Show simple`

![example](https://vgy.me/lDKJB8.gif)

**Comment by buimichael** [comment]
Thanks @fasib !
