### ISSUE TITLE
[Suggestion] Add seperate changelogs for each of the different specs

### ISSUE THREAD

**Issue by buimichael** [MartijnHols/WoWAnalyzer#37]
As an end user you are most likely only interested in knowing the new stuff for your class. Instead of having the user to search/filter that information (and developers tagging each line with the class name), instead add a changelog for each spec.

**Comment by MartijnHols** [comment]
Sounds like a good idea, will look into it when I can

**Comment by buimichael** [comment]
A suggestion to this:
GUI: Under "Changes" title, have an expandable div for each spec (and core). 
Each spec folder contains their own changelog file.
