### ISSUE TITLE
[MW Monk] - NaN showing for spells with 0 casts

### ISSUE THREAD

**Issue by brigzzy** [MartijnHols/WoWAnalyzer#42]
**What browser are you using?**
Chrome Version 58.0.3029.110 (64-bit)

**Link to an example report with the issue**
https://wowanalyzer.com/#/report/xdYRBNc4WV78Z32p/1/Fizaw

**Expected behavior**
Mana tea shows "NaNK mana" when the spell is not used.  SG also shows NaN stacks.  Obvious fix is for me to actually use the spells, but in case I forget, the value of the variables that are used for storing those values should be initialized with a value of 0.  

![nank-mana](https://cloud.githubusercontent.com/assets/6279621/26561500/dbd978f4-4473-11e7-9220-29b9a655fbf8.png)

**Comment by anom0ly** [comment]
Thanks for the catch.

Updating code now to catch these scenarios.

**Comment by brigzzy** [comment]
No problem-o, loving the tool!
