### ISSUE TITLE
[Resto Druid] Add cultivation healing

### ISSUE THREAD

**Issue by buimichael** [MartijnHols/WoWAnalyzer#47]
Should consists of two parts: 

* Healing from cultivation 
* Healing from increased mastery stack.

Also add suggestions and severity levels:

Example:
Severiity: Minor < 8%, Average < 6%, Major <4%
Suggestion text: "Your healing from Cultivation could be improved, you may considering selecting another talent" x%

**Comment by MartijnHols** [comment]
Grouped in #55
