### ISSUE TITLE
[Resto Druid] Add spring blossoms healing

### ISSUE THREAD

**Issue by buimichael** [MartijnHols/WoWAnalyzer#48]
Should consists of two parts: 

* Healing from spring blossoms 
* Healing from increased mastery stack.

Also add suggestions and severity levels:

Example:
Severiity: Minor < 7%, Average < 5%, Major <3%
Suggestion text: "Your healing from Spring Blossoms could be improved, you may considering selecting another talent" x%

**Comment by MartijnHols** [comment]
Grouped in #55
