### ISSUE TITLE
Invalid key specified 

### ISSUE THREAD

**Issue by Errtuz** [MartijnHols/WoWAnalyzer#62]
**What browser are you using?**
Firefox 53.03

**Link to an example report with the issue**
https://www.warcraftlogs.com/reports/L18cDC2tgKGpr4z7/

**Expected behavior**
Hey ! I was hoping to use your tool to analyse my log, but when I try to analyse it, I get "Invalid key specified" - I am an idiot, so very probable I'mn doing something wrong, any chance to enlighten me what :) ?

**Comment by MartijnHols** [comment]
WCL API is currently down;

> Experiencing an attack through the WCL Web API. For now I'm going to have to disable it completely until I can figure out how to harden it against the attack in the future.

**Comment by Errtuz** [comment]
not an idiot then, thanks !

**Comment by MartijnHols** [comment]
Should be fixed!

**Comment by Errtuz** [comment]
Hi ! 

Yes, there's a change, i@m getting slightly different error now ;)

![image](https://cloud.githubusercontent.com/assets/29132327/26736612/c1e2b05c-47be-11e7-93cd-9e570c55d4ac.png)

**Comment by Errtuz** [comment]
ok, it's all working now, could I still be a bit of an ass and ask, why my character is not available for analysis ? it's Errtuz.

**Comment by anom0ly** [comment]
If you are Errtuz on EU-Draenor, and are a mage, the tool currently only supports healers.
