### ISSUE TITLE
Disc Priest Evanglism

### ISSUE THREAD

**Issue by Miyanos** [MartijnHols/WoWAnalyzer#86]
this is one of my logs from M botanist
at 0:57 I evang at 14 atonement, which you can easily see from the replay part
while in the analyzer it shows 9
since i cast evang instantly after my 2nd Pwr
looks like analyzer didnt count  the 2nd PWR
because i can easily see that the whole 14 atonetment get prolonged from its falling timing

**Comment by Miyanos** [comment]
![03](https://user-images.githubusercontent.com/29539276/27279479-b7fd52f8-54b2-11e7-87c0-762dc787827b.jpg)
![04](https://user-images.githubusercontent.com/29539276/27279477-b7491f54-54b2-11e7-9d49-3a421a1131a2.jpg)

**Comment by MartijnHols** [comment]
Do you have a log where you think this is happening?

**Comment by Miyanos** [comment]
https://www.warcraftlogs.com/reports/Vpd1nHcC7yATz98F#fight=1&type=healing

**Comment by rp4rk** [comment]
![image](https://user-images.githubusercontent.com/8212881/27303740-a9d09dc6-5533-11e7-8cf3-00455509580f.png)
I believe the parser is working as intended, and this is an artifact of the game's netcode. As you can see, the Atonement from your second PWR cast don't register until *slightly* after you cast PWR.

**Comment by rp4rk** [comment]
Leaving this here for future ref:

![image](https://user-images.githubusercontent.com/8212881/27304341-a4e516aa-5535-11e7-8269-f54c50b3bd65.png)

**Comment by Miyanos** [comment]
thank you very much. anyway its only a data issue and wont have any negative impact in the game.
