### ISSUE TITLE
Two devotion aura

### ISSUE THREAD

**Issue by jmossetc** [MartijnHols/WoWAnalyzer#97]
**What browser are you using?**
Firefox 

**Link to an example report with the issue**
https://wowanalyzer.com/report/CDFpQKaTgMLtHqZc/12/Thuul

Devotion aura and aura of Mercy is being registered while it shouldn't. I don't know why it gives me a value for aura of Devotion
**Expected behavior**
Aura of Devotion drps shouldn't be displayed

**Comment by MartijnHols** [comment]
Hey thanks a lot for the report! It should have been fixed in e6ea5b7cc2eff81b9e09a70244333edb9766c142.
